# Generated by Django 4.1.3 on 2023-03-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregi',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='userregi',
            old_name='phonenumber',
            new_name='Phonenumber',
        ),
        migrations.RenameField(
            model_name='userregi',
            old_name='uploadid',
            new_name='Uploadid',
        ),
        migrations.AddField(
            model_name='userregi',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregi',
            name='Password',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
